name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GENERATOR: Ninja
  BUILD_ARGS: -v
  JCPP_LOG_LEVEL: debug
  JCPP_LOG_CONSOLE: enable

jobs:
  package-source-tar-gz:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-source.tar.gz
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}.tar.gz

  package-source-zip:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-source.zip
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}.zip

  build-linux-x86_64:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - run: git clone https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack -C ${{env.BUILD_TYPE}} --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-linux-x86_64
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}-linux-x86_64.tar.gz

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build --exclude-from-file ${{github.workspace}}/src/.github/workflows/ctestexclude-linux-manylinux_2_28-x86_64.txt -VV

  build-linux-aarch64:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install libffi
      run: sudo apt install libffi-dev

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack -C ${{env.BUILD_TYPE}} --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-linux-aarch64
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}-linux-aarch64.tar.gz

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build -VV

  build-linux-aarch64-debug:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build -VV

  build-linux-aarch64-clang:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build -VV

  build-linux-u24-04-aarch64:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build -VV

  build-macos-x86_64:
    runs-on: macos-15-intel

    steps:
    - name: Install libffi
      run: brew install libffi

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack -C ${{env.BUILD_TYPE}} --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-macos-x86_64
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}-macos-x86_64.tar.gz

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build --exclude-from-file ${{github.workspace}}/src/.github/workflows/ctestexclude-macos.txt -VV

  build-macos-aarch64:
    runs-on: macos-15

    steps:
    - name: Install libffi
      run: brew install libffi

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack -C ${{env.BUILD_TYPE}} --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-macos-aarch64
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}-macos-aarch64.tar.gz

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build --exclude-from-file ${{github.workspace}}/src/.github/workflows/ctestexclude-macos.txt -VV

  build-macos26-aarch64:
    runs-on: macos-26

    steps:
    - name: Install libffi
      run: brew install libffi

    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build --exclude-from-file ${{github.workspace}}/src/.github/workflows/ctestexclude-macos.txt -VV

  build-windows-x86_64:
    runs-on: windows-2025

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure build
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack -C ${{env.BUILD_TYPE}} --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-windows-x86_64
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}-windows-x86_64.zip

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build -VV

  build-windows-aarch64:
    runs-on: windows-11-arm

    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7

    - uses: actions/checkout@v4
      with:
        path: src

    - name: Configure build
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: arm64

    - name: Configure CMake
      run: cmake -G "${{env.GENERATOR}}" -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{steps.get-version-id.outputs.id}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_WINDOWS_KITS_10_DIR="C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0"

    - name: Build
      run: cmake --build ${{github.workspace}}/build ${{env.BUILD_ARGS}}

    - name: Package
      run: cpack -C ${{env.BUILD_TYPE}} --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-windows-aarch64
        path: ${{github.workspace}}/java.base-${{steps.get-version-id.outputs.id}}-windows-aarch64.zip

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build --exclude-from-file ${{github.workspace}}/src/.github/workflows/ctestexclude-windows-aarch64.txt -VV

  release:
    needs: [package-source-tar-gz,package-source-zip,build-linux-x86_64,build-linux-aarch64,build-macos-x86_64,build-macos-aarch64,build-windows-x86_64,build-windows-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get tag or commit id
      id: get-version-id
      uses: iawia002/get-tag-or-commit-id@v1
      with:
        length: 7
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-source.tar.gz
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-source.zip
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-linux-x86_64
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-linux-aarch64
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-macos-x86_64
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-macos-aarch64
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-windows-x86_64
    - uses: actions/download-artifact@v5
      with:
        name: java.base-${{steps.get-version-id.outputs.id}}-windows-aarch64
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          java.base-${{steps.get-version-id.outputs.id}}.tar.gz
          java.base-${{steps.get-version-id.outputs.id}}.zip
          java.base-${{steps.get-version-id.outputs.id}}-linux-x86_64.tar.gz
          java.base-${{steps.get-version-id.outputs.id}}-linux-aarch64.tar.gz
          java.base-${{steps.get-version-id.outputs.id}}-macos-x86_64.tar.gz
          java.base-${{steps.get-version-id.outputs.id}}-macos-aarch64.tar.gz
          java.base-${{steps.get-version-id.outputs.id}}-windows-x86_64.zip
          java.base-${{steps.get-version-id.outputs.id}}-windows-aarch64.zip